name: StarNEig base tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  base tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependences
      run: sudo apt-get install gfortran libopenblas-dev libopenmpi-dev libscalapack-openmpi-dev libstarpu-dev libgsl-dev
    - name: Configure
      run: cmake .
    - name: Build
      run: make
    - name: Test
      run: make test
