name: StarNEig base tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install xmllint
      run: sudo apt install gfortran libstarpu-dev
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: make test
      run: make test
