name: StarNEig manual

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the hash
        run: echo ::set-env name=SHORT_HASH::${GITHUB_SHA:0:10}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependences
        run: sudo apt-get install texlive-full doxygen

      - name: Built manual
        run: |
          echo "latest (${{ env.SHORT_HASH }})" > version.txt
          mkdir build_docs
          cd build_docs/
            cmake ../docs/
            make
          cd ../
          mkdir latest
          cp -r build_docs/html build_docs/starneig_manual.pdf latest/

      - name: Deploy manual
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: latest
          TARGET_FOLDER: latest
          COMMIT_MESSAGE: "Upload ${{ env.SHORT_HASH }} documentation"
