name: StarNEig tests

on:
  push:
    branches:
      - 'master'
      - 'v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'v*'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependences
        run: |
          sudo apt-get update
          sudo apt-get install gfortran libopenblas-dev libopenmpi-dev \
            libscalapack-openmpi-dev libstarpu-dev libgsl-dev

      - name: Configure
        run: |
          mkdir build
          cd build/
          cmake ../

      - name: Build
        run: |
          cd build/
          make

      - name: Test
        run: |
          cd build/
          alias mpirun='mpirun --oversubscribe'
          CTEST_OUTPUT_ON_FAILURE=1 \
          OPENBLAS_NUM_THREADS=1 \
          OMPI_ALLOW_RUN_AS_ROOT=1 \
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
          make test
